name: Jobs

on:
  # Pull requests targeting main
  pull_request:
    branches: [ main ]
    
    # opened: when a PR is created
    # reopened: when a PR is reopened
    # synchronize: when commits are pushed to an open PR
    types: [opened, reopened, synchronize]

  # Manually triggered
  workflow_dispatch:    

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release
